docker run --rm --name kafka -p '9092:9092' -v "kafka_data:/bitnami" \
       -e BITNAMI_DEBUG=yes \
       -e KAFKA_ENABLE_KRAFT=yes \
       -e KAFKA_CFG_PROCESS_ROLES=broker,controller \
       -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
       -e KAFKA_CFG_LISTENERS=CONTROLLER://:9093,PLAINTEXT://:9092,DOCKER_INTERNAL://:19092 \
       -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER_INTERNAL:PLAINTEXT \
       -e KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
       -e KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true \
       -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093 \
       -e ALLOW_PLAINTEXT_LISTENER=yes \
       -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,DOCKER_INTERNAL://kafka:19092, \
       -e KAFKA_CFG_BROKER_ID=1 \
       -e KAFKA_BROKER_ID=1 \
       -e KAFKA_CFG_DELETE_TOPIC_ENABLE=true \
       bitnami/kafka:3.4.0